namespace WindowsFormsApp1
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            DevExpress.XtraEditors.TileItemElement tileItemElement123 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement124 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement125 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement126 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame19 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement127 = new DevExpress.XtraEditors.TileItemElement();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            DevExpress.XtraEditors.TileItemFrame tileItemFrame20 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement128 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement129 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement130 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement131 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement132 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement133 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement134 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame21 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement135 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame22 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement136 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement137 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement138 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement139 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement140 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement141 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement142 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement143 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement144 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement145 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement146 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement147 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement148 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement149 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement150 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement151 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement152 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement153 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement154 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement155 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement156 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement157 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement158 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame23 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement159 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame24 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement160 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement161 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement162 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement163 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement164 = new DevExpress.XtraEditors.TileItemElement();
            this.ribbonPage2 = new DevExpress.XtraBars.Ribbon.RibbonPage();
            this.ribbonPage3 = new DevExpress.XtraBars.Ribbon.RibbonPage();
            this.tileControl1 = new DevExpress.XtraEditors.TileControl();
            this.baseAppTiles = new DevExpress.XtraEditors.TileGroup();
            this.tileItem1 = new DevExpress.XtraEditors.TileItem();
            this.weatherTile = new DevExpress.XtraEditors.TileItem();
            this.dateTimeTile = new DevExpress.XtraEditors.TileItem();
            this.settingsTile = new DevExpress.XtraEditors.TileItem();
            this.productTiles = new DevExpress.XtraEditors.TileGroup();
            this.expiringProductsTile = new DevExpress.XtraEditors.TileItem();
            this.productOffersTile = new DevExpress.XtraEditors.TileItem();
            this.extraTiles = new DevExpress.XtraEditors.TileGroup();
            this.calendarTile = new DevExpress.XtraEditors.TileItem();
            this.findRecipesTile = new DevExpress.XtraEditors.TileItem();
            this.fridgeCameraTile = new DevExpress.XtraEditors.TileItem();
            this.radioTile = new DevExpress.XtraEditors.TileItem();
            this.allProductsTile = new DevExpress.XtraEditors.TileItem();
            this.browserTile = new DevExpress.XtraEditors.TileItem();
            this.tileItem2 = new DevExpress.XtraEditors.TileItem();
            this.simpleButton1 = new DevExpress.XtraEditors.SimpleButton();
            this.SuspendLayout();
            // 
            // ribbonPage2
            // 
            this.ribbonPage2.Name = "ribbonPage2";
            this.ribbonPage2.Text = "ribbonPage2";
            // 
            // ribbonPage3
            // 
            this.ribbonPage3.Name = "ribbonPage3";
            this.ribbonPage3.Text = "ribbonPage3";
            // 
            // tileControl1
            // 
            this.tileControl1.BackColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.tileControl1.Cursor = System.Windows.Forms.Cursors.Default;
            this.tileControl1.Groups.Add(this.baseAppTiles);
            this.tileControl1.Groups.Add(this.productTiles);
            this.tileControl1.Groups.Add(this.extraTiles);
            this.tileControl1.Location = new System.Drawing.Point(0, 1);
            this.tileControl1.MaxId = 18;
            this.tileControl1.Name = "tileControl1";
            this.tileControl1.Orientation = System.Windows.Forms.Orientation.Vertical;
            this.tileControl1.Size = new System.Drawing.Size(582, 663);
            this.tileControl1.TabIndex = 16;
            this.tileControl1.Text = "tileControl1";
            this.tileControl1.Click += new System.EventHandler(this.tileControl1_Click);
            // 
            // baseAppTiles
            // 
            this.baseAppTiles.Items.Add(this.tileItem1);
            this.baseAppTiles.Items.Add(this.weatherTile);
            this.baseAppTiles.Items.Add(this.dateTimeTile);
            this.baseAppTiles.Items.Add(this.settingsTile);
            this.baseAppTiles.Name = "baseAppTiles";
            this.baseAppTiles.Text = "Date and Time";
            // 
            // tileItem1
            // 
            this.tileItem1.AppearanceItem.Normal.BackColor = System.Drawing.Color.Green;
            this.tileItem1.AppearanceItem.Normal.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.tileItem1.AppearanceItem.Normal.Font = new System.Drawing.Font("Adobe Heiti Std R", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tileItem1.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem1.AppearanceItem.Normal.Options.UseBorderColor = true;
            this.tileItem1.AppearanceItem.Normal.Options.UseFont = true;
            this.tileItem1.CurrentFrameIndex = 1;
            tileItemElement123.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement123.Appearance.Hovered.Options.UseFont = true;
            tileItemElement123.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement123.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement123.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement123.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 12.25F);
            tileItemElement123.Appearance.Normal.Options.UseFont = true;
            tileItemElement123.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement123.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement123.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement123.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement123.Appearance.Selected.Options.UseFont = true;
            tileItemElement123.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement123.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement123.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement123.Text = "Temperature";
            tileItemElement123.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement123.TextLocation = new System.Drawing.Point(4, 8);
            tileItemElement124.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement124.Appearance.Hovered.Options.UseFont = true;
            tileItemElement124.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement124.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement124.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement124.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            tileItemElement124.Appearance.Normal.Options.UseFont = true;
            tileItemElement124.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement124.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement124.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement124.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement124.Appearance.Selected.Options.UseFont = true;
            tileItemElement124.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement124.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement124.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement124.Text = "3 °C";
            tileItemElement124.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement124.TextLocation = new System.Drawing.Point(4, 27);
            tileItemElement125.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement125.Appearance.Hovered.Options.UseFont = true;
            tileItemElement125.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement125.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement125.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement125.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 12.25F);
            tileItemElement125.Appearance.Normal.Options.UseFont = true;
            tileItemElement125.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement125.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement125.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement125.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement125.Appearance.Selected.Options.UseFont = true;
            tileItemElement125.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement125.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement125.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement125.Text = "Humidity";
            tileItemElement125.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement125.TextLocation = new System.Drawing.Point(4, 55);
            tileItemElement126.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement126.Appearance.Hovered.Options.UseFont = true;
            tileItemElement126.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement126.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement126.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement126.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            tileItemElement126.Appearance.Normal.Options.UseFont = true;
            tileItemElement126.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement126.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement126.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement126.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement126.Appearance.Selected.Options.UseFont = true;
            tileItemElement126.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement126.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement126.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement126.Text = "50%";
            tileItemElement126.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement126.TextLocation = new System.Drawing.Point(4, 70);
            this.tileItem1.Elements.Add(tileItemElement123);
            this.tileItem1.Elements.Add(tileItemElement124);
            this.tileItem1.Elements.Add(tileItemElement125);
            this.tileItem1.Elements.Add(tileItemElement126);
            this.tileItem1.FrameAnimationInterval = 5000;
            tileItemFrame19.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement127.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement127.Image")));
            tileItemElement127.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement127.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement127.ImageSize = new System.Drawing.Size(70, 70);
            tileItemElement127.ImageToTextAlignment = DevExpress.XtraEditors.TileControlImageToTextAlignment.Top;
            tileItemElement127.Text = "Temperature";
            tileItemFrame19.Elements.Add(tileItemElement127);
            tileItemFrame19.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame19.Image")));
            tileItemFrame19.Interval = 5000;
            tileItemFrame20.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement128.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement128.Appearance.Hovered.Options.UseFont = true;
            tileItemElement128.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement128.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement128.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement128.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 12.25F);
            tileItemElement128.Appearance.Normal.Options.UseFont = true;
            tileItemElement128.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement128.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement128.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement128.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement128.Appearance.Selected.Options.UseFont = true;
            tileItemElement128.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement128.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement128.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement128.Text = "Temperature";
            tileItemElement128.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement128.TextLocation = new System.Drawing.Point(4, 8);
            tileItemElement129.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement129.Appearance.Hovered.Options.UseFont = true;
            tileItemElement129.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement129.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement129.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement129.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            tileItemElement129.Appearance.Normal.Options.UseFont = true;
            tileItemElement129.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement129.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement129.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement129.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement129.Appearance.Selected.Options.UseFont = true;
            tileItemElement129.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement129.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement129.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement129.Text = "3 °C";
            tileItemElement129.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement129.TextLocation = new System.Drawing.Point(4, 27);
            tileItemElement130.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement130.Appearance.Hovered.Options.UseFont = true;
            tileItemElement130.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement130.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement130.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement130.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 12.25F);
            tileItemElement130.Appearance.Normal.Options.UseFont = true;
            tileItemElement130.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement130.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement130.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement130.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement130.Appearance.Selected.Options.UseFont = true;
            tileItemElement130.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement130.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement130.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement130.Text = "Humidity";
            tileItemElement130.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement130.TextLocation = new System.Drawing.Point(4, 55);
            tileItemElement131.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement131.Appearance.Hovered.Options.UseFont = true;
            tileItemElement131.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement131.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement131.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement131.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            tileItemElement131.Appearance.Normal.Options.UseFont = true;
            tileItemElement131.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement131.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement131.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement131.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement131.Appearance.Selected.Options.UseFont = true;
            tileItemElement131.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement131.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement131.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement131.Text = "50%";
            tileItemElement131.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement131.TextLocation = new System.Drawing.Point(4, 70);
            tileItemFrame20.Elements.Add(tileItemElement128);
            tileItemFrame20.Elements.Add(tileItemElement129);
            tileItemFrame20.Elements.Add(tileItemElement130);
            tileItemFrame20.Elements.Add(tileItemElement131);
            this.tileItem1.Frames.Add(tileItemFrame19);
            this.tileItem1.Frames.Add(tileItemFrame20);
            this.tileItem1.Id = 15;
            this.tileItem1.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.tileItem1.Name = "tileItem1";
            this.tileItem1.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem1_ItemClick);
            // 
            // weatherTile
            // 
            this.weatherTile.AppearanceItem.Normal.BackColor = System.Drawing.Color.Teal;
            this.weatherTile.AppearanceItem.Normal.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.weatherTile.AppearanceItem.Normal.Font = new System.Drawing.Font("Adobe Heiti Std R", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.weatherTile.AppearanceItem.Normal.Options.UseBackColor = true;
            this.weatherTile.AppearanceItem.Normal.Options.UseBorderColor = true;
            this.weatherTile.AppearanceItem.Normal.Options.UseFont = true;
            this.weatherTile.CurrentFrameIndex = 1;
            tileItemElement132.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement132.Appearance.Hovered.Options.UseFont = true;
            tileItemElement132.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement132.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement132.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement132.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement132.Appearance.Normal.Options.UseFont = true;
            tileItemElement132.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement132.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement132.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement132.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement132.Appearance.Selected.Options.UseFont = true;
            tileItemElement132.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement132.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement132.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement132.Text = "Weather";
            tileItemElement132.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement132.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement133.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement133.Appearance.Hovered.Options.UseFont = true;
            tileItemElement133.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement133.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement133.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement133.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            tileItemElement133.Appearance.Normal.Options.UseFont = true;
            tileItemElement133.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement133.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement133.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement133.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement133.Appearance.Selected.Options.UseFont = true;
            tileItemElement133.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement133.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement133.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement133.Text = "Pireaus";
            tileItemElement133.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement133.TextLocation = new System.Drawing.Point(4, 27);
            tileItemElement134.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement134.Appearance.Hovered.Options.UseFont = true;
            tileItemElement134.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement134.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement134.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement134.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            tileItemElement134.Appearance.Normal.Options.UseFont = true;
            tileItemElement134.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement134.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement134.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement134.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement134.Appearance.Selected.Options.UseFont = true;
            tileItemElement134.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement134.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement134.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement134.Text = "20 °C";
            tileItemElement134.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement134.TextLocation = new System.Drawing.Point(4, 59);
            this.weatherTile.Elements.Add(tileItemElement132);
            this.weatherTile.Elements.Add(tileItemElement133);
            this.weatherTile.Elements.Add(tileItemElement134);
            tileItemFrame21.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement135.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement135.Image")));
            tileItemElement135.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement135.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement135.ImageSize = new System.Drawing.Size(70, 70);
            tileItemElement135.ImageToTextAlignment = DevExpress.XtraEditors.TileControlImageToTextAlignment.Top;
            tileItemElement135.Text = "Weather";
            tileItemFrame21.Elements.Add(tileItemElement135);
            tileItemFrame21.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame21.Image")));
            tileItemFrame22.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement136.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement136.Appearance.Hovered.Options.UseFont = true;
            tileItemElement136.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement136.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement136.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement136.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement136.Appearance.Normal.Options.UseFont = true;
            tileItemElement136.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement136.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement136.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement136.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement136.Appearance.Selected.Options.UseFont = true;
            tileItemElement136.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement136.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement136.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement136.Text = "Weather";
            tileItemElement136.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement136.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement137.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement137.Appearance.Hovered.Options.UseFont = true;
            tileItemElement137.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement137.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement137.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement137.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            tileItemElement137.Appearance.Normal.Options.UseFont = true;
            tileItemElement137.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement137.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement137.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement137.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement137.Appearance.Selected.Options.UseFont = true;
            tileItemElement137.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement137.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement137.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement137.Text = "Pireaus";
            tileItemElement137.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement137.TextLocation = new System.Drawing.Point(4, 27);
            tileItemElement138.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement138.Appearance.Hovered.Options.UseFont = true;
            tileItemElement138.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement138.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement138.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement138.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            tileItemElement138.Appearance.Normal.Options.UseFont = true;
            tileItemElement138.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement138.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement138.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement138.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement138.Appearance.Selected.Options.UseFont = true;
            tileItemElement138.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement138.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement138.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement138.Text = "20 °C";
            tileItemElement138.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement138.TextLocation = new System.Drawing.Point(4, 59);
            tileItemFrame22.Elements.Add(tileItemElement136);
            tileItemFrame22.Elements.Add(tileItemElement137);
            tileItemFrame22.Elements.Add(tileItemElement138);
            this.weatherTile.Frames.Add(tileItemFrame21);
            this.weatherTile.Frames.Add(tileItemFrame22);
            this.weatherTile.Id = 1;
            this.weatherTile.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.weatherTile.Name = "weatherTile";
            this.weatherTile.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.weatherTile_ItemClick);
            // 
            // dateTimeTile
            // 
            this.dateTimeTile.AppearanceItem.Normal.BackColor = System.Drawing.Color.Olive;
            this.dateTimeTile.AppearanceItem.Normal.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.dateTimeTile.AppearanceItem.Normal.Font = new System.Drawing.Font("Adobe Heiti Std R", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dateTimeTile.AppearanceItem.Normal.Options.UseBackColor = true;
            this.dateTimeTile.AppearanceItem.Normal.Options.UseBorderColor = true;
            this.dateTimeTile.AppearanceItem.Normal.Options.UseFont = true;
            tileItemElement139.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 49F);
            tileItemElement139.Appearance.Hovered.Options.UseFont = true;
            tileItemElement139.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement139.Appearance.Hovered.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
            tileItemElement139.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.Character;
            tileItemElement139.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement139.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 30F);
            tileItemElement139.Appearance.Normal.Options.UseFont = true;
            tileItemElement139.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement139.Appearance.Normal.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
            tileItemElement139.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.Character;
            tileItemElement139.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement139.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 49F);
            tileItemElement139.Appearance.Selected.Options.UseFont = true;
            tileItemElement139.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement139.Appearance.Selected.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
            tileItemElement139.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.Character;
            tileItemElement139.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement139.MaxWidth = 100;
            tileItemElement139.Text = "15:45";
            tileItemElement139.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement140.Appearance.Normal.Font = new System.Drawing.Font("Tahoma", 10.25F);
            tileItemElement140.Appearance.Normal.Options.UseFont = true;
            tileItemElement140.Text = "Monday,";
            tileItemElement140.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleLeft;
            tileItemElement140.TextLocation = new System.Drawing.Point(5, 14);
            tileItemElement141.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement141.Appearance.Hovered.Options.UseFont = true;
            tileItemElement141.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement141.Appearance.Hovered.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
            tileItemElement141.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement141.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement141.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            tileItemElement141.Appearance.Normal.Options.UseFont = true;
            tileItemElement141.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement141.Appearance.Normal.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
            tileItemElement141.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement141.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement141.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement141.Appearance.Selected.Options.UseFont = true;
            tileItemElement141.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement141.Appearance.Selected.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
            tileItemElement141.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement141.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement141.MaxWidth = 140;
            tileItemElement141.Text = "5/2/2018";
            tileItemElement141.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            tileItemElement141.TextLocation = new System.Drawing.Point(5, -8);
            this.dateTimeTile.Elements.Add(tileItemElement139);
            this.dateTimeTile.Elements.Add(tileItemElement140);
            this.dateTimeTile.Elements.Add(tileItemElement141);
            this.dateTimeTile.Id = 2;
            this.dateTimeTile.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.dateTimeTile.Name = "dateTimeTile";
            // 
            // settingsTile
            // 
            this.settingsTile.AppearanceItem.Normal.BackColor = System.Drawing.Color.Purple;
            this.settingsTile.AppearanceItem.Normal.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.settingsTile.AppearanceItem.Normal.Font = new System.Drawing.Font("Adobe Heiti Std R", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.settingsTile.AppearanceItem.Normal.Options.UseBackColor = true;
            this.settingsTile.AppearanceItem.Normal.Options.UseBorderColor = true;
            this.settingsTile.AppearanceItem.Normal.Options.UseFont = true;
            tileItemElement142.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement142.Image")));
            tileItemElement142.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement142.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement142.ImageSize = new System.Drawing.Size(70, 70);
            tileItemElement142.ImageToTextAlignment = DevExpress.XtraEditors.TileControlImageToTextAlignment.Top;
            tileItemElement142.Text = "Settings";
            this.settingsTile.Elements.Add(tileItemElement142);
            this.settingsTile.Id = 3;
            this.settingsTile.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.settingsTile.Name = "settingsTile";
            // 
            // productTiles
            // 
            this.productTiles.Items.Add(this.expiringProductsTile);
            this.productTiles.Items.Add(this.productOffersTile);
            this.productTiles.Name = "productTiles";
            this.productTiles.Text = "tileGroup2";
            // 
            // expiringProductsTile
            // 
            this.expiringProductsTile.AppearanceItem.Normal.BackColor = System.Drawing.Color.Firebrick;
            this.expiringProductsTile.AppearanceItem.Normal.BorderColor = System.Drawing.Color.Maroon;
            this.expiringProductsTile.AppearanceItem.Normal.Options.UseBackColor = true;
            this.expiringProductsTile.AppearanceItem.Normal.Options.UseBorderColor = true;
            tileItemElement143.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement143.Appearance.Hovered.Options.UseFont = true;
            tileItemElement143.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement143.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement143.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement143.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement143.Appearance.Normal.Options.UseFont = true;
            tileItemElement143.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement143.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement143.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement143.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement143.Appearance.Selected.Options.UseFont = true;
            tileItemElement143.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement143.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement143.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement143.MaxWidth = 160;
            tileItemElement143.Text = "Expiring Soon";
            tileItemElement143.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement143.TextLocation = new System.Drawing.Point(75, 0);
            tileItemElement144.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement144.Appearance.Hovered.Options.UseFont = true;
            tileItemElement144.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement144.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement144.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement144.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement144.Appearance.Normal.Options.UseFont = true;
            tileItemElement144.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement144.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement144.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement144.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement144.Appearance.Selected.Options.UseFont = true;
            tileItemElement144.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement144.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement144.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement144.MaxWidth = 160;
            tileItemElement144.Text = "Milk in 4 days";
            tileItemElement144.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement144.TextLocation = new System.Drawing.Point(75, 29);
            tileItemElement145.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement145.Appearance.Hovered.Options.UseFont = true;
            tileItemElement145.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement145.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement145.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement145.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement145.Appearance.Normal.Options.UseFont = true;
            tileItemElement145.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement145.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement145.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement145.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement145.Appearance.Selected.Options.UseFont = true;
            tileItemElement145.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement145.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement145.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement145.MaxWidth = 160;
            tileItemElement145.Text = "Eggs in 5 days";
            tileItemElement145.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement145.TextLocation = new System.Drawing.Point(75, 45);
            tileItemElement146.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement146.Appearance.Hovered.Options.UseFont = true;
            tileItemElement146.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement146.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement146.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement146.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement146.Appearance.Normal.Options.UseFont = true;
            tileItemElement146.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement146.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement146.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement146.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement146.Appearance.Selected.Options.UseFont = true;
            tileItemElement146.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement146.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement146.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement146.MaxWidth = 160;
            tileItemElement146.Text = "Bread in 5 days";
            tileItemElement146.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement146.TextLocation = new System.Drawing.Point(75, 61);
            tileItemElement147.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement147.Image")));
            tileItemElement147.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement147.ImageLocation = new System.Drawing.Point(4, 8);
            tileItemElement147.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement147.ImageSize = new System.Drawing.Size(64, 64);
            this.expiringProductsTile.Elements.Add(tileItemElement143);
            this.expiringProductsTile.Elements.Add(tileItemElement144);
            this.expiringProductsTile.Elements.Add(tileItemElement145);
            this.expiringProductsTile.Elements.Add(tileItemElement146);
            this.expiringProductsTile.Elements.Add(tileItemElement147);
            this.expiringProductsTile.Id = 10;
            this.expiringProductsTile.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.expiringProductsTile.Name = "expiringProductsTile";
            this.expiringProductsTile.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.expiringProductsTile_ItemClick);
            // 
            // productOffersTile
            // 
            this.productOffersTile.AppearanceItem.Normal.BackColor = System.Drawing.Color.MidnightBlue;
            this.productOffersTile.AppearanceItem.Normal.BorderColor = System.Drawing.Color.Navy;
            this.productOffersTile.AppearanceItem.Normal.Options.UseBackColor = true;
            this.productOffersTile.AppearanceItem.Normal.Options.UseBorderColor = true;
            tileItemElement148.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement148.Appearance.Hovered.Options.UseFont = true;
            tileItemElement148.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement148.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement148.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement148.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement148.Appearance.Normal.Options.UseFont = true;
            tileItemElement148.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement148.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement148.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement148.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement148.Appearance.Selected.Options.UseFont = true;
            tileItemElement148.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement148.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement148.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement148.MaxWidth = 160;
            tileItemElement148.Text = "On Offer";
            tileItemElement148.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement148.TextLocation = new System.Drawing.Point(75, 0);
            tileItemElement149.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement149.Appearance.Hovered.Options.UseFont = true;
            tileItemElement149.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement149.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement149.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement149.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement149.Appearance.Normal.Options.UseFont = true;
            tileItemElement149.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement149.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement149.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement149.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement149.Appearance.Selected.Options.UseFont = true;
            tileItemElement149.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement149.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement149.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement149.MaxWidth = 160;
            tileItemElement149.Text = "Milk 50% off";
            tileItemElement149.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement149.TextLocation = new System.Drawing.Point(75, 29);
            tileItemElement150.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement150.Appearance.Hovered.Options.UseFont = true;
            tileItemElement150.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement150.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement150.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement150.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement150.Appearance.Normal.Options.UseFont = true;
            tileItemElement150.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement150.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement150.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement150.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement150.Appearance.Selected.Options.UseFont = true;
            tileItemElement150.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement150.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement150.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement150.MaxWidth = 160;
            tileItemElement150.Text = "Bread 50% off";
            tileItemElement150.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement150.TextLocation = new System.Drawing.Point(75, 45);
            tileItemElement151.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement151.Appearance.Hovered.Options.UseFont = true;
            tileItemElement151.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement151.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement151.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement151.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement151.Appearance.Normal.Options.UseFont = true;
            tileItemElement151.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement151.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement151.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement151.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement151.Appearance.Selected.Options.UseFont = true;
            tileItemElement151.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement151.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement151.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement151.MaxWidth = 160;
            tileItemElement151.Text = "Butter 30% off";
            tileItemElement151.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement151.TextLocation = new System.Drawing.Point(75, 61);
            tileItemElement152.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement152.Image")));
            tileItemElement152.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement152.ImageLocation = new System.Drawing.Point(4, 8);
            tileItemElement152.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement152.ImageSize = new System.Drawing.Size(64, 64);
            this.productOffersTile.Elements.Add(tileItemElement148);
            this.productOffersTile.Elements.Add(tileItemElement149);
            this.productOffersTile.Elements.Add(tileItemElement150);
            this.productOffersTile.Elements.Add(tileItemElement151);
            this.productOffersTile.Elements.Add(tileItemElement152);
            this.productOffersTile.Id = 11;
            this.productOffersTile.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.productOffersTile.Name = "productOffersTile";
            this.productOffersTile.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.productOffersTile_ItemClick);
            // 
            // extraTiles
            // 
            this.extraTiles.Items.Add(this.calendarTile);
            this.extraTiles.Items.Add(this.findRecipesTile);
            this.extraTiles.Items.Add(this.fridgeCameraTile);
            this.extraTiles.Items.Add(this.radioTile);
            this.extraTiles.Items.Add(this.allProductsTile);
            this.extraTiles.Items.Add(this.browserTile);
            this.extraTiles.Items.Add(this.tileItem2);
            this.extraTiles.Name = "extraTiles";
            this.extraTiles.Text = "tileGroup1";
            // 
            // calendarTile
            // 
            this.calendarTile.AppearanceItem.Normal.BackColor = System.Drawing.Color.Purple;
            this.calendarTile.AppearanceItem.Normal.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.calendarTile.AppearanceItem.Normal.Options.UseBackColor = true;
            this.calendarTile.AppearanceItem.Normal.Options.UseBorderColor = true;
            tileItemElement153.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement153.Appearance.Hovered.Options.UseFont = true;
            tileItemElement153.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement153.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement153.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement153.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 14F);
            tileItemElement153.Appearance.Normal.Options.UseFont = true;
            tileItemElement153.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement153.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement153.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement153.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement153.Appearance.Selected.Options.UseFont = true;
            tileItemElement153.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement153.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement153.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement153.MaxWidth = 145;
            tileItemElement153.Text = "Today\'s Events:";
            tileItemElement153.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement153.TextLocation = new System.Drawing.Point(4, 11);
            tileItemElement154.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 49F);
            tileItemElement154.Appearance.Hovered.Options.UseFont = true;
            tileItemElement154.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement154.Appearance.Hovered.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
            tileItemElement154.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.Character;
            tileItemElement154.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement154.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 49F);
            tileItemElement154.Appearance.Normal.Options.UseFont = true;
            tileItemElement154.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement154.Appearance.Normal.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
            tileItemElement154.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.Character;
            tileItemElement154.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement154.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 49F);
            tileItemElement154.Appearance.Selected.Options.UseFont = true;
            tileItemElement154.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement154.Appearance.Selected.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
            tileItemElement154.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.Character;
            tileItemElement154.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement154.MaxWidth = 100;
            tileItemElement154.Text = "5";
            tileItemElement154.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement154.TextLocation = new System.Drawing.Point(0, -15);
            tileItemElement155.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement155.Appearance.Hovered.Options.UseFont = true;
            tileItemElement155.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement155.Appearance.Hovered.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
            tileItemElement155.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement155.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement155.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement155.Appearance.Normal.Options.UseFont = true;
            tileItemElement155.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement155.Appearance.Normal.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
            tileItemElement155.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement155.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement155.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement155.Appearance.Selected.Options.UseFont = true;
            tileItemElement155.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement155.Appearance.Selected.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
            tileItemElement155.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement155.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement155.MaxWidth = 70;
            tileItemElement155.Text = "Monday";
            tileItemElement155.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleRight;
            tileItemElement155.TextLocation = new System.Drawing.Point(0, 15);
            tileItemElement156.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            tileItemElement156.Appearance.Normal.Options.UseFont = true;
            tileItemElement156.Text = "events";
            tileItemElement156.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleLeft;
            tileItemElement156.TextLocation = new System.Drawing.Point(10, 0);
            this.calendarTile.Elements.Add(tileItemElement153);
            this.calendarTile.Elements.Add(tileItemElement154);
            this.calendarTile.Elements.Add(tileItemElement155);
            this.calendarTile.Elements.Add(tileItemElement156);
            this.calendarTile.Id = 14;
            this.calendarTile.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.calendarTile.Name = "calendarTile";
            // 
            // findRecipesTile
            // 
            this.findRecipesTile.AppearanceItem.Normal.BackColor = System.Drawing.Color.SaddleBrown;
            this.findRecipesTile.AppearanceItem.Normal.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.findRecipesTile.AppearanceItem.Normal.Options.UseBackColor = true;
            this.findRecipesTile.AppearanceItem.Normal.Options.UseBorderColor = true;
            tileItemElement157.Appearance.Normal.Font = new System.Drawing.Font("Adobe Fan Heiti Std B", 10F, System.Drawing.FontStyle.Bold);
            tileItemElement157.Appearance.Normal.Options.UseFont = true;
            tileItemElement157.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement157.Image")));
            tileItemElement157.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement157.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement157.ImageSize = new System.Drawing.Size(70, 70);
            tileItemElement157.ImageToTextAlignment = DevExpress.XtraEditors.TileControlImageToTextAlignment.Top;
            tileItemElement157.Text = "Find Recipes";
            this.findRecipesTile.Elements.Add(tileItemElement157);
            this.findRecipesTile.Id = 4;
            this.findRecipesTile.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.findRecipesTile.Name = "findRecipesTile";
            this.findRecipesTile.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.findRecipesTile_ItemClick);
            // 
            // fridgeCameraTile
            // 
            this.fridgeCameraTile.AppearanceItem.Normal.BackColor = System.Drawing.Color.Teal;
            this.fridgeCameraTile.AppearanceItem.Normal.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.fridgeCameraTile.AppearanceItem.Normal.Options.UseBackColor = true;
            this.fridgeCameraTile.AppearanceItem.Normal.Options.UseBorderColor = true;
            this.fridgeCameraTile.CurrentFrameIndex = 1;
            tileItemElement158.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement158.Image")));
            tileItemElement158.ImageLocation = new System.Drawing.Point(-10, 10);
            tileItemElement158.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement158.ImageSize = new System.Drawing.Size(120, 120);
            tileItemElement158.Text = "";
            this.fridgeCameraTile.Elements.Add(tileItemElement158);
            this.fridgeCameraTile.FrameAnimationInterval = 5000;
            tileItemFrame23.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement159.Appearance.Normal.Font = new System.Drawing.Font("Adobe Fan Heiti Std B", 10F, System.Drawing.FontStyle.Bold);
            tileItemElement159.Appearance.Normal.Options.UseFont = true;
            tileItemElement159.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement159.Image")));
            tileItemElement159.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement159.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Squeeze;
            tileItemElement159.ImageSize = new System.Drawing.Size(80, 80);
            tileItemElement159.ImageToTextAlignment = DevExpress.XtraEditors.TileControlImageToTextAlignment.Top;
            tileItemElement159.Text = "Fridge Camera";
            tileItemFrame23.Elements.Add(tileItemElement159);
            tileItemFrame23.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame23.Image")));
            tileItemFrame24.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement160.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement160.Image")));
            tileItemElement160.ImageLocation = new System.Drawing.Point(-10, 10);
            tileItemElement160.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement160.ImageSize = new System.Drawing.Size(120, 120);
            tileItemElement160.Text = "";
            tileItemFrame24.Elements.Add(tileItemElement160);
            tileItemFrame24.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame24.Image")));
            this.fridgeCameraTile.Frames.Add(tileItemFrame23);
            this.fridgeCameraTile.Frames.Add(tileItemFrame24);
            this.fridgeCameraTile.Id = 5;
            this.fridgeCameraTile.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.fridgeCameraTile.Name = "fridgeCameraTile";
            this.fridgeCameraTile.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.fridgeCameraTile_ItemClick);
            // 
            // radioTile
            // 
            this.radioTile.AppearanceItem.Normal.BackColor = System.Drawing.Color.Maroon;
            this.radioTile.AppearanceItem.Normal.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.radioTile.AppearanceItem.Normal.Options.UseBackColor = true;
            this.radioTile.AppearanceItem.Normal.Options.UseBorderColor = true;
            tileItemElement161.Appearance.Normal.Font = new System.Drawing.Font("Adobe Fan Heiti Std B", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
            tileItemElement161.Appearance.Normal.Options.UseFont = true;
            tileItemElement161.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement161.Image")));
            tileItemElement161.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement161.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement161.ImageSize = new System.Drawing.Size(80, 80);
            tileItemElement161.ImageToTextAlignment = DevExpress.XtraEditors.TileControlImageToTextAlignment.Top;
            tileItemElement161.Text = "Radio";
            this.radioTile.Elements.Add(tileItemElement161);
            this.radioTile.Id = 6;
            this.radioTile.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.radioTile.Name = "radioTile";
            // 
            // allProductsTile
            // 
            this.allProductsTile.AppearanceItem.Normal.BackColor = System.Drawing.Color.Navy;
            this.allProductsTile.AppearanceItem.Normal.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.allProductsTile.AppearanceItem.Normal.Options.UseBackColor = true;
            this.allProductsTile.AppearanceItem.Normal.Options.UseBorderColor = true;
            tileItemElement162.Appearance.Normal.Font = new System.Drawing.Font("Adobe Fan Heiti Std B", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
            tileItemElement162.Appearance.Normal.Options.UseFont = true;
            tileItemElement162.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement162.Image")));
            tileItemElement162.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement162.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement162.ImageSize = new System.Drawing.Size(70, 70);
            tileItemElement162.ImageToTextAlignment = DevExpress.XtraEditors.TileControlImageToTextAlignment.Top;
            tileItemElement162.Text = "All Products";
            this.allProductsTile.Elements.Add(tileItemElement162);
            this.allProductsTile.Id = 7;
            this.allProductsTile.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.allProductsTile.Name = "allProductsTile";
            this.allProductsTile.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.allProductsTile_ItemClick);
            // 
            // browserTile
            // 
            this.browserTile.AppearanceItem.Normal.BackColor = System.Drawing.Color.DodgerBlue;
            this.browserTile.AppearanceItem.Normal.BorderColor = System.Drawing.Color.Blue;
            this.browserTile.AppearanceItem.Normal.Options.UseBackColor = true;
            this.browserTile.AppearanceItem.Normal.Options.UseBorderColor = true;
            tileItemElement163.Appearance.Normal.Font = new System.Drawing.Font("Adobe Fan Heiti Std B", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
            tileItemElement163.Appearance.Normal.Options.UseFont = true;
            tileItemElement163.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement163.Image")));
            tileItemElement163.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement163.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement163.ImageSize = new System.Drawing.Size(70, 70);
            tileItemElement163.ImageToTextAlignment = DevExpress.XtraEditors.TileControlImageToTextAlignment.Top;
            tileItemElement163.Text = "Browser";
            this.browserTile.Elements.Add(tileItemElement163);
            this.browserTile.Id = 16;
            this.browserTile.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.browserTile.Name = "browserTile";
            this.browserTile.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.browserTile_ItemClick);
            // 
            // tileItem2
            // 
            this.tileItem2.AppearanceItem.Normal.BackColor = System.Drawing.Color.Olive;
            this.tileItem2.AppearanceItem.Normal.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.tileItem2.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem2.AppearanceItem.Normal.Options.UseBorderColor = true;
            tileItemElement164.Appearance.Normal.Font = new System.Drawing.Font("Adobe Fan Heiti Std B", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
            tileItemElement164.Appearance.Normal.Options.UseFont = true;
            tileItemElement164.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement164.Image")));
            tileItemElement164.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement164.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement164.ImageSize = new System.Drawing.Size(80, 80);
            tileItemElement164.ImageToTextAlignment = DevExpress.XtraEditors.TileControlImageToTextAlignment.Top;
            tileItemElement164.Text = "Add more";
            this.tileItem2.Elements.Add(tileItemElement164);
            this.tileItem2.Id = 17;
            this.tileItem2.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.tileItem2.Name = "tileItem2";
            // 
            // simpleButton1
            // 
            this.simpleButton1.ButtonStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
            this.simpleButton1.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("simpleButton1.ImageOptions.Image")));
            this.simpleButton1.Location = new System.Drawing.Point(12, 12);
            this.simpleButton1.Name = "simpleButton1";
            this.simpleButton1.Size = new System.Drawing.Size(42, 40);
            this.simpleButton1.TabIndex = 17;
            this.simpleButton1.Visible = false;
            this.simpleButton1.Click += new System.EventHandler(this.simpleButton1_Click);
            // 
            // MainForm
            // 
            this.Appearance.BackColor = System.Drawing.Color.Black;
            this.Appearance.Options.UseBackColor = true;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(583, 665);
            this.Controls.Add(this.simpleButton1);
            this.Controls.Add(this.tileControl1);
            this.FormBorderEffect = DevExpress.XtraEditors.FormBorderEffect.None;
            this.Name = "MainForm";
            this.ShowIcon = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.Shown += new System.EventHandler(this.MainForm_Shown);
            this.ResumeLayout(false);

        }

        #endregion
        private DevExpress.XtraBars.Ribbon.RibbonPage ribbonPage2;
        private DevExpress.XtraBars.Ribbon.RibbonPage ribbonPage3;
        private DevExpress.XtraEditors.TileControl tileControl1;
        private DevExpress.XtraEditors.TileGroup baseAppTiles;
        private DevExpress.XtraEditors.TileItem tileItem1;
        private DevExpress.XtraEditors.TileItem weatherTile;
        private DevExpress.XtraEditors.TileItem dateTimeTile;
        private DevExpress.XtraEditors.TileItem settingsTile;
        private DevExpress.XtraEditors.TileGroup productTiles;
        private DevExpress.XtraEditors.TileItem expiringProductsTile;
        private DevExpress.XtraEditors.TileItem productOffersTile;
        private DevExpress.XtraEditors.TileGroup extraTiles;
        private DevExpress.XtraEditors.TileItem calendarTile;
        private DevExpress.XtraEditors.TileItem findRecipesTile;
        private DevExpress.XtraEditors.TileItem fridgeCameraTile;
        private DevExpress.XtraEditors.TileItem radioTile;
        private DevExpress.XtraEditors.TileItem allProductsTile;
        private DevExpress.XtraEditors.TileItem browserTile;
        private DevExpress.XtraEditors.TileItem tileItem2;
        private DevExpress.XtraEditors.SimpleButton simpleButton1;
    }
}

